<div class="container">
    <div class="row d-flex justify-content-center">
        <div class="container-logout">
            <a href="/logout" title="Sair"><svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-x-circle-fill" viewBox="0 0 16 16">
                <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0M5.354 4.646a.5.5 0 1 0-.708.708L7.293 8l-2.647 2.646a.5.5 0 0 0 .708.708L8 8.707l2.646 2.647a.5.5 0 0 0 .708-.708L8.707 8l2.647-2.646a.5.5 0 0 0-.708-.708L8 7.293z"/>
            </svg></a>
        </div>
        <div class="col-4 container-logo">
            <div class="img-btec pt-5">
                <img src="../image/logo.png" width="175px">
            </div>
        </div>
    </div>
</div>
<div class="container container-img-logo">
    <div class="row d-flex justify-content-center">
        <div class="col-12 col-md-2 mb-3 text-center d-flex flex-column align-items-center">
            <img class="mb-3" src="../image/logo-varuna.png" title="PORTAL VARUNA" width="103px">
            <span class="d-none d-md-block">
                <a href="#" class="link-portais">PORTAL VARUNA</a>
            </span>
        </div>
        <div class="col-12 col-md-2 mb-3 text-center d-flex flex-column align-items-center">
            <img class="mb-3" src="../image/logo-labore.png" title="PORTAL LABORE" width="103px">
            <span class="d-none d-md-block">
                <a href="#" class="link-portais">PORTAL LABORE</a>
            </span>
        </div>
        <div class="col-12 col-md-2 mb-3 text-center d-flex flex-column align-items-center">
            <a href="/oficina"><img class="mb-3" src="../image/logo-oficina.png" title="PORTAL OFICINA" width="103px"></a>
            <span class="d-none d-md-block">
                <a href="/oficina" class="link-portais">PORTAL OFICINA</a>
            </span>
        </div>
        <div class="col-12 col-md-2 mb-3 text-center d-flex flex-column align-items-center">
            <img class="mb-3" src="../image/logo-obras.png" title="PORTAL OBRAS" width="103px">
            <span class="d-none d-md-block">
                <a href="#" class="link-portais">PORTAL OBRAS</a>
            </span>
        </div>
        <div class="col-12 col-md-2 mb-3 text-center d-flex flex-column align-items-center">
            <img class="mt-1 mb-4" src="../image/logo-powerbi.png" title="POWER BI" width="90px">
            <span class="d-none d-md-block">
                <a href="#" class="link-portais">POWER BI</a>
            </span>
        </div>
    </div>
</div>


