<div class="container">
    <div class="row d-flex justify-content-center">
        <div class="col-4 container-logo">
            <div class="img-btec pt-5">
                <img src="../image/logo.png">
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row d-flex justify-content-center">
        <div class="col-2">
            <img class="mb-3" src="../image/logo-varuna.png">
            <br>
            <a href="#" class="link-portais">PORTAL VARUNA</a>
        </div>
        <div class="col-2">
            <img class="mb-3" src="../image/logo-varuna.png">
            <br>
            <a href="#" class="link-portais">PORTAL LABORE</a>
        </div>
        <div class="col-2">
            <img class="mb-3" src="../image/logo-varuna.png">
            <br>
            <a href="#" class="link-portais">PORTAL OFICINA</a>
        </div>
        <div class="col-2">
            <img class="mb-3" src="../image/logo-varuna.png">
            <br>
            <a href="#" class="link-portais">&nbsp;&nbsp;PORTAL OBRAS</a>
        </div>
        <div class="col-2">
            <img class="mb-3" src="../image/logo-varuna.png">
            <br>
            <a href="#" class="link-portais">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;POWER BI</a>
        </div>
    </div>
</div>

