<div class="container">
    <div class="row d-flex justify-content-center">
        <div class="col-4 container-logo">
            <div class="img-btec pt-5">
                <img src="../image/logo.png">
            </div>
        </div>
    </div>
</div>
<div class="container container-img-logo">
    <div class="row d-flex justify-content-center">
        <div class="col-12 col-md-2 mb-3 text-center d-flex flex-column align-items-center">
            <img class="mb-3" src="../image/logo-varuna.png" title="PORTAL VARUNA" width="103px">
            <span class="d-none d-md-block">
                <a href="#" class="link-portais">PORTAL VARUNA</a>
            </span>
        </div>
        <div class="col-12 col-md-2 mb-3 text-center d-flex flex-column align-items-center">
            <img class="mb-3" src="../image/logo-varuna.png" title="PORTAL LABORE" width="103px">
            <span class="d-none d-md-block">
                <a href="#" class="link-portais">PORTAL LABORE</a>
            </span>
        </div>
        <div class="col-12 col-md-2 mb-3 text-center d-flex flex-column align-items-center">
            <img class="mb-3" src="../image/logo-varuna.png" title="PORTAL OFICINA" width="103px">
            <span class="d-none d-md-block">
                <a href="#" class="link-portais">PORTAL OFICINA</a>
            </span>
        </div>
        <div class="col-12 col-md-2 mb-3 text-center d-flex flex-column align-items-center">
            <img class="mb-3" src="../image/logo-varuna.png" title="PORTAL OBRAS" width="103px">
            <span class="d-none d-md-block">
                <a href="#" class="link-portais">PORTAL OBRAS</a>
            </span>
        </div>
        <div class="col-12 col-md-2 mb-3 text-center d-flex flex-column align-items-center">
            <img class="mb-3" src="../image/logo-powerbi.png" title="POWER BI" width="103px">
            <span class="d-none d-md-block">
                <a href="#" class="link-portais">POWER BI</a>
            </span>
        </div>
    </div>
</div>


