<div class="container">
    <div class="row">
        <div class="col-6">

            <form action="#" method="post">
                <input type="text" placeholder="Digite seu nome" class="form-control">
                <input type="text" placeholder="Digite sua senha" class="form-control">
                <div class="d-grid gap-2">
                    <button class="btn btn-primary">LOGIN</button>
                </div>
            </form>

        </div>
    </div>
</div>